name: Exec tests at Pull-Request.

on:
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: testing
          MYSQL_USER: actions
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests Feature
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD:
        run: php artisan test tests/Feature

      - name: Execute tests FeatureSeparate/BuyingItemTransactionRollback
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD:
        run: |
          DB_DATABASE=testing php artisan migrate:refresh
          php artisan test tests/FeatureSeparate/BuyingItemTransactionRollbackTest.php

      - name: Execute tests FeatureSeparate/BuyingItemDeadlock
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD:
        run: |
          DB_DATABASE=testing php artisan migrate:refresh
          php artisan test tests/FeatureSeparate/BuyingItemDeadlockTest.php

      - name: Execute tests FeatureSeparate/BuyingItemDeadlockAvoidance
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD:
        run: |
          DB_DATABASE=testing php artisan migrate:refresh
          php artisan test tests/FeatureSeparate/BuyingItemDeadlockAvoidanceTest.php
